packages:
  - '.'
allowBuilds:
  '@embedded-postgres/windows-x64': true
  '@embedded-postgres/linux-x64': true
  '@embedded-postgres/darwin-arm64': true
  esbuild: true
  unrs-resolver: true
  sharp: true
  '@tailwindcss/oxide': true
