/**
 * Checklist definitions extracted VERBATIM from the reference
 * `Admin_Data_Entry_Engine.html` SCHEMA constant (22 categories).
 *
 * - `key` values are stable identifiers — never change them once deployed.
 * - `type` "LOG" = category-level fields only (no item rows).
 * - `type` "CHECK" = item rows with OP / CL marks + defect/comment + photo.
 * - The reference also defines an unused "eval" type (rating + comment); the
 *   enum preserves EVAL for forward-compatibility but no category uses it.
 *
 * Do not retype or "clean up" item wording — it mirrors the source engine.
 */
export interface ChecklistCategoryDef {
  key: string;
  name: string;
  type: "CHECK" | "LOG";
  topFields?: string[];
  items?: string[];
}

/** Sign-off fields preserved from the reference engine (SIGN_FIELDS). */
export const SIGN_FIELDS = [
  "Duty Electrician / Technician Sign",
  "A.M Admin",
  "Manager Admin",
] as const;

export const CHECKLIST_DEFINITIONS: ChecklistCategoryDef[] = [
  {
    key: "genset_500",
    name: "500 KVA Genset",
    type: "LOG",
    topFields: [
      "Opening Reading",
      "Closing Reading",
      "Total Hours",
      "Fuel Used (Ltr)",
      "Reading Done By",
      "Entered By",
      "Verified By",
    ],
  },
  {
    key: "genset_250",
    name: "250 KVA Genset",
    type: "LOG",
    topFields: [
      "Opening Reading",
      "Closing Reading",
      "Total Hours",
      "Fuel Used (Ltr)",
      "Reading Done By",
      "Entered By",
      "Verified By",
    ],
  },
  {
    key: "fuel_refill_500",
    name: "500 KVA Fuel Refill",
    type: "LOG",
    topFields: ["Liters Refilled", "Refilled By", "Verified By", "Remarks"],
  },
  {
    key: "fuel_refill_250",
    name: "250 KVA Fuel Refill",
    type: "LOG",
    topFields: ["Liters Refilled", "Refilled By", "Verified By", "Remarks"],
  },
  {
    key: "genset_operational",
    name: "Generator Checklist",
    type: "CHECK",
    items: [
      "Physical Inspection",
      "Generator Room Camera",
      "Diesel tank Condition",
      "Fire Extinguisher",
      "Control Panel Functional",
      "Startup Test (Cold Start)",
      "Automatic Transfer Switch (ATS)",
      "Output Voltage Within Limits",
      "Load Test Performance",
      "Fuel System (No leaks, clean filter)",
      "Engine Oil Level & Condition",
      "Emergency Stop Functional",
      "Coolant Level & Temperature",
      "Exhaust Condition (Smoke, odor)",
      "Noise/Vibration Levels",
      "Fan Belts",
      "Gaskets",
      "Fan Drive",
      "Time (Opening & Closing)",
      "Diesel tank leveler check",
    ],
  },
  {
    key: "firefighting_pumps",
    name: "Firefighting Pumps",
    type: "CHECK",
    items: [
      "Jockey Pump",
      "Electric Pump",
      "Diesel Pump",
      "Pump Coupling",
      "Pressure Gauges",
      "Suction/Discharge Valves",
      "Non-return Valve",
      "Motor (Electric)",
      "Battery (Diesel Pump)",
      "Engine Oil Level (Diesel Pump)",
      "Cooling System (Diesel)",
      "Time (Opening & Closing)",
      "Emergency Lights Functioning",
      "No Leaks (Water/Fuel/Oil)",
      "Electrical Panels Secured",
      "Access Unobstructed",
      "Auto Start (Electric Pump)",
      "Auto Start (Diesel Pump — Pressure Drop Simulated)",
      "Pressure Relief Valve Test",
      "System Pressure Drop (Jockey Pump Test)",
      "Fire hose reels at all designated points",
      "Fire Hose at Boundary area",
    ],
  },
  {
    key: "swimming_pool",
    name: "Swimming Pool",
    type: "CHECK",
    items: [
      "Number of Sofa",
      "Number of Pool Loungers",
      "Number of Side Table",
      "Pool Floor Neat & Clean",
      "Water is apparently Clean",
      "Pool skimming is done",
      "Pool Side door working Fine",
      "Time (Opening & Closing)",
      "Pool is working Fine (Pool Pump)",
      "All Lights are functional",
    ],
  },
  {
    key: "cafeteria",
    name: "Cafeteria",
    type: "CHECK",
    items: [
      "Clean & disinfect toilet bowl",
      "Check for visible stains/debris",
      "Clean & disinfect toilet seat/lid",
      "Ensure fittings secure",
      "Wipe & sanitize flush handle",
      "Check flushing mechanism",
      "Clean sink, faucet, handles",
      "Ensure proper drainage",
      "Clean & wipe down mirrors",
      "Sweep floor to remove debris",
      "Mop floor",
      "Empty & replace trash bags",
      "Ensure toilet paper/soap/towels stocked",
    ],
  },
  {
    key: "cinema",
    name: "Cinema",
    type: "CHECK",
    items: [
      "Vacuum/sweep floors to remove debris",
      "Dust & clean projector, screens, speakers & equipment",
      "Empty trash bins & replace liners",
      "Clean spills/stains on seats promptly",
      "Ensure emergency exits clear & unobstructed",
      "Number of Chairs",
      "Projector & Speakers count",
      "Time (Opening & Closing)",
    ],
  },
  {
    key: "gym",
    name: "Gym / Fitness Center",
    type: "CHECK",
    items: [
      "All Ceiling Lights are functional",
      "Air Conditioners are working fine",
      "Treadmill's Electric Power is ok",
      "Electrical Power is ok",
      "Dumbell Sets count",
      "Plates count",
      "Balls count",
      "Amplifier count",
      "Sweep floors to remove debris",
      "Toilet is washed, neat & clean",
      "All Equipments are Clean",
      "Main Door is Working Fine",
      "Pool Side door is working Fine",
      "Toilet's Door is working Fine",
      "Soap Dispenser",
    ],
  },
  {
    key: "kids_play_area",
    name: "Kids Play Area",
    type: "CHECK",
    items: [
      "Kids Play Items intact",
      "All Ceiling Lights are functional",
      "Air Conditioners are working fine",
      "Number of Bean Bags",
      "Number of chairs & table",
      "Number of table games",
      "Number of stuffed toys",
    ],
  },
  {
    key: "garbage_chute",
    name: "Garbage Chute",
    type: "CHECK",
    items: [
      "Chute door functioning properly",
      "No blockage / overflow",
      "Odor control check",
      "Area around chute clean",
      "Chute room locked & secured",
    ],
  },
  {
    key: "housekeeping",
    name: "Housekeeping (Common Areas)",
    type: "CHECK",
    items: [
      "Common area floors clean",
      "Corridors dusted",
      "Entrance mats clean",
      "Trash bins emptied",
      "Windows/glass cleaned",
      "All equipment clean",
    ],
  },
  {
    key: "rooftop",
    name: "Rooftop",
    type: "CHECK",
    items: [
      "Floor is Neat & Clean",
      "Water plants daily",
      "Clean Chairs and Tables",
      "Genset area check",
      "Diesel tank & water tank check",
      "Elevator room & electric room check",
    ],
  },
  {
    key: "terraces",
    name: "Terraces (per floor)",
    type: "CHECK",
    items: [
      "6th Floor Terrace",
      "7th Floor Terrace",
      "8th Floor Terrace",
      "9th Floor Terrace",
      "10th Floor Terrace",
      "11th Floor Terrace",
      "Roof Top Terrace",
    ],
  },
  {
    key: "all_floor_meter",
    name: "All Floor Meter Rooms",
    type: "CHECK",
    items: [
      "Basement 2",
      "Ground Floor",
      "1st Floor",
      "2nd Floor",
      "3rd Floor",
      "4th Floor",
      "5th Floor",
      "6th Floor",
      "7th Floor",
      "8th Floor",
      "9th Floor",
      "10th Floor",
      "11th Floor",
    ],
  },
  {
    key: "cctv_room",
    name: "CCTV / IT Room",
    type: "CHECK",
    items: [
      "All Cameras Check",
      "WiFi",
      "Network Switch",
      "All DVRs",
      "Mouse",
      "UPS Check",
      "Battery Condition",
      "Fire Extinguisher",
      "Air conditioning",
      "Fire sensor panel",
      "DP Box Check",
    ],
  },
  {
    key: "lt_room",
    name: "LT Room",
    type: "CHECK",
    items: [
      "Camera Check",
      "DP Box Check",
      "Electrical WAPDA Meter",
      "ATS System Check",
      "AC Check",
      "Fire Extinguisher",
      "Electrical Generator Meter of Apartments",
      "All Electrical System check",
    ],
  },
  {
    key: "fire_fighting",
    name: "Fire Fighting (General)",
    type: "CHECK",
    items: [
      "Fire hose reels intact",
      "Fire extinguishers charged & tagged",
      "Emergency exits clear",
      "Fire alarm panel functional",
      "Sprinkler heads unobstructed",
    ],
  },
  {
    key: "lift",
    name: "Lift",
    type: "CHECK",
    items: [
      "Cabin and Counter Weight Shoes",
      "Floor Level",
      "Stool Wire Rope",
      "Servicing of Wire Break",
      "Cleaning of Cabin + Counter Ceiling",
      "Blower Fan",
      "Buffer Position",
      "Landing Push Plate Condition",
      "Landing Door Lock / Door Contact",
      "Car Door Operator / Cam / Sensor",
      "Landing Door Sill Cleaning",
      "Motor Foundation",
      "Motor Pulley Helping Pulley Checking",
      "Control Panel Servicing",
      "Control Card Wiring Checking",
      "Limit Switch Checking",
      "Reed Switch Checking",
      "Magnet Position Checking",
      "Main Switch (MCCB) Checking",
      "VVVF Inverter Drive",
      "Call Push Button",
      "Air conditioning",
      "Bell",
      "Others",
    ],
  },
  {
    key: "tubewell",
    name: "Tubewell",
    type: "CHECK",
    items: [
      "Corrosion, rust cracks or wrapping tang",
      "Rust/leak welded joints pipe work",
      "Supporting structure condition",
      "Cleaning",
      "Water Leakage",
      "Overall condition",
      "Maintenance need if any",
    ],
  },
  {
    key: "basement_2",
    name: "Basement 2 (Motor Pump)",
    type: "CHECK",
    items: [
      "Panel Box",
      "Auto system",
      "Gate Valve",
      "Motor 1",
      "Transfer Pump 15hp 1",
      "Transfer Pump 15hp 2 (Manual backup)",
      "DB Box Operational",
      "Pressure Gauge",
      "Motor 2",
      "Light",
      "Leakage",
      "Cleaning",
      "Service",
    ],
  },
];

/** Stable key for a field label, e.g. "Fuel Used (Ltr)" → "fuel_used_ltr". */
export function fieldKeyFromLabel(label: string): string {
  return label
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}
